# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, RETURN, Editor, exec, omarchy-launch-editor
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian /home/keigo/documents/obsidian"
bindd = SUPER SHIFT, S, Screenshot (region), exec, omarchy-capture-screenshot

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai/new"

# Password and email
bindd = SUPER SHIFT, E, Auto-Email,exec, sleep 0.2 && wtype 'keigohealy2028@u.northwestern.edu'

bindd = SUPER SHIFT, N, Brown Noise, exec, uwsm-app -- xdg-open /home/keigo/media/videos/brown_noise.m4a
# bind = SUPER SHIFT, N, exec, xdg-open /home/keigo/media/videos/brown_noise.m4a

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu